language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.linux.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below